version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    networks:
      - trivia_network

networks:
  trivia_network:
    driver: bridge
