# Generated by Django 4.0.4 on 2022-04-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_category_alter_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question_id',
            new_name='question',
        ),
    ]
